CREATE TABLE IF NOT EXISTS casbin_rule (
  id INT IDENTITY(1, 1) PRIMARY KEY,
  ptype NVARCHAR(12) NOT NULL,
  v0 NVARCHAR(128) NOT NULL,
  v1 NVARCHAR(128) NOT NULL,
  v2 NVARCHAR(128) NOT NULL,
  v3 NVARCHAR(128) NOT NULL,
  v4 NVARCHAR(128) NOT NULL,
  v5 NVARCHAR(128) NOT NULL,
  CONSTRAINT unique_key_casbin_adapter UNIQUE(ptype, v0, v1, v2, v3, v4, v5)
);